### ISSUE TITLE
relatedEntities or relatedMolecularEntity?

### ISSUE THREAD

**Issue by aegururaj** [datatagsuite/schema#26]
The documentation needs to be updated to reflect the latest relatedEntities (it still shows up as relatedMolecularEntity)

**Comment by agbeltran** [comment]
Thanks @aegururaj - I'll investigate

**Comment by agbeltran** [comment]
This is now fixed and you can see the model again here: 
https://datatagsuite.github.io/docs/html/dats.html
or the schema here:
https://datatagsuite.github.io/schema/molecular_entity_schema.json
