### ISSUE TITLE
The schema for relatedEntities is missing

### ISSUE THREAD

**Issue by aegururaj** [datatagsuite/schema#27]
This would possibly be the molecular entity schema?

**Comment by agbeltran** [comment]
@aegururaj I imagine you are referring that the different types of relatedEntities are missing from the visualisation of the schema as per this link:

https://fairsharing.github.io/JSONSchema-documenter/index.html?parameters=%7B%22target%22:%22https://w3id.org/dats/schema/molecular_entity_schema.json%22,%22display%22:%22grid%22%7D

This is not a problem of the schema but of the tool to visualise it. We will look into it.

**Comment by aegururaj** [comment]
How do we represent the identifiers for the relatedEntities, taxonomic information etc?
Previous mapping had the following:
1) _source'.'orthology'[*].'confidence' - Dataset.isAbout.MolecularEntity.relatedEntities.characteristics.Dimension.values
2) _source'.'orthology'[*].'gene1AgrPrimaryId' -Dataset.isAbout.MolecularEntity.relatedEntities.Identifiers.identifier
3) _source'.'orthology'[*].'gene1Species' - Dataset.isAbout.MolecularEntity.relatedEntities.taxonomy.TaxonomicInformation.identifier
4) _source'.'orthology'[*].'gene1SpeciesName' - Dataset.isAbout.MolecularEntity.relatedEntities.taxonomy.TaxonomicInformation.name
5) _source'.'orthology'[*].'gene1Symbol' - Dataset.isAbout.MolecularEntity.relatedEntities.AlternateIdentifiers.identifier

**Comment by agbeltran** [comment]
What before was a specific 'MolecularEntity' now it can be any 'object' (that itself can be a 'MolecularEntity'). 

e.g.
_source'.'orthology'[*].'confidence' - Dataset.isAbout.MolecularEntity.relatedEntities.object.characteristics.Dimension.values

where now the 'object' property points to a MolecularEntity with specific characteristics .

**Comment by aegururaj** [comment]
I assumed so but wanted to confirm. Thanks for the clarification, Alejandra ☺

**Comment by agbeltran** [comment]
I created the visualization issue in the json-schema documenter repo: https://github.com/FAIRsharing/JSONSchema-documenter/issues/34
