### ISSUE TITLE
Add conformsTo to Dataset

### ISSUE THREAD

**Issue by agbeltran** [datatagsuite/schema#30]
we currently have 'conformsTo Standard' for DatasetDistributions, but we don't have it at the level of the Dataset; this would be to align with [DCAT](https://w3c.github.io/dxwg/dcat/#Property:resource_conformsto)

**Comment by proccaserra** [comment]
Do I get right that the DCAT use case here relating Standards to DataSet is that related to for example  QC Standards, so a specific type of standards . Does DCAT constrain this more specifically?
